import { RtrStatus } from "@/graphql/generated/graphql";
import { IconType } from "react-icons/lib";
import { LuCheck, LuX, LuClock, LuEye, LuSend, LuPencil } from "react-icons/lu";

export const color: Record<string, string> = {
	[RtrStatus.Pending]: "yellow",
	[RtrStatus.Signed]: "green",
	[RtrStatus.Rejected]: "red",
	[RtrStatus.Expired]: "gray",
	[RtrStatus.Viewed]: "blue",
	[RtrStatus.Sent]: "purple",
	[RtrStatus.Draft]: "orange",
};

export const statusIcon: Record<string, IconType> = {
	[RtrStatus.Pending]: LuClock,
	[RtrStatus.Signed]: LuCheck,
	[RtrStatus.Rejected]: LuX,
	[RtrStatus.Expired]: LuClock,
	[RtrStatus.Viewed]: LuEye,
	[RtrStatus.Sent]: LuSend,
	[RtrStatus.Draft]: LuPencil,
};

export const states = [
	{ name: "Alabama", value: "alabama", code: "AL" },
	{ name: "Alaska", value: "alaska", code: "AK" },
	{ name: "Arizona", value: "arizona", code: "AZ" },
	{ name: "Arkansas", value: "arkansas", code: "AR" },
	{ name: "California", value: "california", code: "CA" },
	{ name: "Colorado", value: "colorado", code: "CO" },
	{ name: "Connecticut", value: "connecticut", code: "CT" },
	{ name: "Delaware", value: "delaware", code: "DE" },
	{ name: "Florida", value: "florida", code: "FL" },
	{ name: "Georgia", value: "georgia", code: "GA" },
	{ name: "Hawaii", value: "hawaii", code: "HI" },
	{ name: "Idaho", value: "idaho", code: "ID" },
	{ name: "Illinois", value: "illinois", code: "IL" },
	{ name: "Indiana", value: "indiana", code: "IN" },
	{ name: "Iowa", value: "iowa", code: "IA" },
	{ name: "Kansas", value: "kansas", code: "KS" },
	{ name: "Kentucky", value: "kentucky", code: "KY" },
	{ name: "Louisiana", value: "louisiana", code: "LA" },
	{ name: "Maine", value: "maine", code: "ME" },
	{ name: "Maryland", value: "maryland", code: "MD" },
	{ name: "Massachusetts", value: "massachusetts", code: "MA" },
	{ name: "Michigan", value: "michigan", code: "MI" },
	{ name: "Minnesota", value: "minnesota", code: "MN" },
	{ name: "Mississippi", value: "mississippi", code: "MS" },
	{ name: "Missouri", value: "missouri", code: "MO" },
	{ name: "Montana", value: "montana", code: "MT" },
	{ name: "Nebraska", value: "nebraska", code: "NE" },
	{ name: "Nevada", value: "nevada", code: "NV" },
	{ name: "New Hampshire", value: "new hampshire", code: "NH" },
	{ name: "New Jersey", value: "new jersey", code: "NJ" },
	{ name: "New Mexico", value: "new mexico", code: "NM" },
	{ name: "New York", value: "", code: "NY" },
	{ name: "North Carolina", value: "north carolina", code: "NC" },
	{ name: "North Dakota", value: "north dakota", code: "ND" },
	{ name: "Ohio", value: "ohio", code: "OH" },
	{ name: "Oklahoma", value: "oklahoma", code: "OK" },
	{ name: "Oregon", value: "oregon", code: "OR" },
	{ name: "Pennsylvania", value: "pennsylvania", code: "PA" },
	{ name: "Rhode Island", value: "rhode island", code: "RI" },
	{ name: "South Carolina", value: "south carolina", code: "SC" },
	{ name: "South Dakota", value: "south dakota", code: "SD" },
	{ name: "Tennessee", value: "tennessee", code: "TN" },
	{ name: "Texas", value: "texas", code: "TX" },
	{ name: "Utah", value: "utah", code: "UT" },
	{ name: "Vermont", value: "vermont", code: "VT" },
	{ name: "Virginia", value: "virginia", code: "VA" },
	{ name: "Washington", value: "washington", code: "WA" },
	{ name: "West Virginia", value: "west virginia", code: "WV" },
	{ name: "Wisconsin", value: "wisconsin", code: "WI" },
	{ name: "Wyoming", value: "wyoming", code: "WY" },
];
