import type { Metadata } from "next";
import { Poppins, Quicksand } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import { AppProviders } from "@/components/providers";
import "quill/dist/quill.snow.css";
import "./globals.css";

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["400", "600", "800"],
});

const quicksand = Quicksand({
	variable: "--font-quicksand",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Right to Represent",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${poppins.variable} ${quicksand.variable}`}>
				<AppProviders>
					<Provider forcedTheme="dark">{children}</Provider>
				</AppProviders>
			</body>
		</html>
	);
}
